print("=== Personal profile Creater ===")
name = input("What is your name? :")
age = input("How old are you? :")
email = input("What your email :")
phone = input("What is your phone number :")
hobby = input("What is your favorite hobby :")

print("== Your profile ==")
print("Name :",name)
print("Age:",age)
print("Email :",email)
print("Phone number :",phone)
print("Favorite hobby :",hobby)